language: python

sudo: false

install: 
    - pip install doc8
    - npm install -g write-good

script:
    - doc8 README.rst
    - aspell README.rst
    - write-good README.rst --weasel --so --thereIs --adverb --cliches
